version: '2.4'
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 9000:9000
    entrypoint: yarn
    command: start
volumes:
  # Making node_modules a named volume prevents the ./app volume mount from
  # clobbering the node_modules directory in the container. Since the volume only
  # has to be named, it doesn't require any configuration directives.
  node_modules:
